images:
  - image: "vaultwarden/server"
    tag: "latest"
    name: "vaultwarden"
  - image: "finab/bark-server"
    tag: "latest"
    name: "bark-server"
  - image: "elasticsearch"
    tag: "7.17.23"
    name: "elasticsearch"
  - image: "mysql"
    tag: "5.7"
    name: "mysql"
