images:
  - image: "docker.io/volcanosh/vc-controller-manager"
    tag: "latest"
    name: "vc-controller-manager"
  - image: "docker.io/volcanosh/vc-scheduler"
    tag: "latest"
    name: "vc-scheduler"

  



