images:
  - image: "ghcr.io/abcdqwerxsa/scion-gemini"
    tag: "latest"
    name: "scion-gemini"
  - image: "ghcr.io/abcdqwerxsa/scion-claude"
    tag: "latest"
    name: "scion-claude"
  - image: "ghcr.io/abcdqwerxsa/scion-codex"
    tag: "latest"
    name: "scion-codex"
  - image: "ghcr.io/abcdqwerxsa/scion-opencode"
    tag: "latest"
    name: "scion-opencode"
