images:
  - image: "vaultwarden/server"
    tag: "latest"
    name: "vaultwarden"
  - image: "finab/bark-server"
    tag: "latest"
    name: "bark-server"
  - image: "elasticsearch"
    tag: "7.17.23"
    name: "elasticsearch"
  - image: "mysql"
    tag: "5.7"
    name: "mysql"
  - image: "hyperf/hyperf"
    tag: "8.3-alpine-v3.20-swoole"
    name: "hyperf"
  - image: "clickhouse"
    tag: "24.8"
    name: "clickhouse"
  - image: "n8nio/n8n"
    tag: "latest"
    name: "n8n"
  - image: "hexdolemonai/lemon-runtime-sandbox"
    tag: "latest"
    name: "lemon-runtime-sandbox"
