name: Mirror Docker Images

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: Mirror Docker images from Docker Hub to Coding
    steps:
      - uses: actions/checkout@v4
      - name: Mirror images
        run: |
          images=$(cat ${{ github.workspace }}/.github/images.yml | yq '.images' -o json)
          matrix=$(echo "$images" | jq -c '.[] | {image: .image, name: .name, tag: .tag}')
          for item in $(echo "$matrix"); do
            image=$(echo $item | jq -r '.image')
            name=$(echo $item | jq -r '.name')
            tag=$(echo $item | jq -r '.tag')
            skopeo copy docker://docker.io/${image}:${tag} \
              docker://${{ secrets.CODING_REGISTRY_URL }}/${{ secrets.CODING_REGISTRY_USERNAME }}/docker/${name}:${tag} \
              --src-creds "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
              --dest-creds "${{ secrets.CODING_USERNAME }}:${{ secrets.CODING_TOKEN }}"
          done
