jobs:
  mirror:
    name: >-
      Mirror ${{ github.event.inputs.name || 'All Images' }}${{ github.event.inputs.version && format(' (version: {0})', github.event.inputs.version) || '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mirror images
        env:
          INPUT_NAME: ${{ github.event.inputs.name }}
          INPUT_VERSION: ${{ github.event.inputs.version }}
        run: |
          images=$(yq -o json '.images' ${{ github.workspace }}/.github/images.yml)

          if [ -n "$INPUT_NAME" ]; then
          matrix=$(echo "$images" | jq -c --arg name "$INPUT_NAME" '.[] | select(.name == $name)')
          else
          matrix=$(echo "$images" | jq -c '.[]')
          fi

          if [ -z "$matrix" ]; then
          echo "No matching images found for name: $INPUT_NAME"
          exit 1
          fi

          echo "$matrix" | while read -r item; do
            image=$(echo "$item" | jq -r '.image')
            name=$(echo "$item" | jq -r '.name')
            default_tag=$(echo "$item" | jq -r '.tag')
            tag=${INPUT_VERSION:-$default_tag}

            echo "Mirroring $image:$tag to docker.cnb.cool/nilpotenter/docker/${name}:${tag}"

            # --- 新增的逻辑判断 ---
            if [[ "$image" == ghcr.io/* ]]; then
              echo "Source is GitHub Container Registry (ghcr.io). Using GITHUB_TOKEN for authentication."
              skopeo copy --all docker://${image}:${tag} \
                docker://docker.cnb.cool/nilpotenter/docker/${name}:${tag} \
                --src-creds "x:${{ secrets.GITHUB_TOKEN }}" \
                --dest-creds "cnb:${{ secrets.CNB_DOCKER_TOKEN }}"
            else
              echo "Source is Docker Hub or another public registry. Using DOCKERHUB_TOKEN for authentication."
              # --- 你原有的逻辑 ---
              skopeo copy --all docker://${image}:${tag} \
                docker://docker.cnb.cool/nilpotenter/docker/${name}:${tag} \
                --src-creds "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
                --dest-creds "cnb:${{ secrets.CNB_DOCKER_TOKEN }}"
            fi
          
            echo "::notice title=Image Published::https://docker.cnb.cool/nilpotenter/docker/${name}:${tag}"
          done
