name: Mirror Docker Images

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/images.yml'
    branches: [ 'main' ]

jobs:
  mirror:
    runs-on: ubuntu-latest
    name: Mirror Docker images from Docker Hub to CNB
    steps:
      - uses: actions/checkout@v4
      - name: Mirror images
        run: |
          images=$(cat ${{ github.workspace }}/.github/images.yml | yq '.images' -o json)
          matrix=$(echo "$images" | jq -c '.[] | {image: .image, name: .name, tag: .tag}')
          for item in $(echo "$matrix"); do
            image=$(echo $item | jq -r '.image')
            name=$(echo $item | jq -r '.name')
            tag=$(echo $item | jq -r '.tag')
            skopeo copy --all docker://docker.io/${image}:${tag} \
              docker://docker.cnb.cool/lufei/docker/${name}:${tag} \
              --src-creds "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" \
              --dest-creds "cnb:${{ secrets.CNB_DOCKER_TOKEN }}"
          done
